/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.uniza.fri.duracik2.gui.reflection;

import java.io.File;
import java.util.concurrent.ExecutionException;
import javax.swing.JFileChooser;
import javax.swing.SwingWorker;

/**
 *
 * @author Unlink
 */
public class FileComponentField extends javax.swing.JPanel {

	private JFileChooser aFileChooser;
	private File aSelected;

	/**
	 * Creates new form FileComponentField
	 *
	 * @param paField
	 */
	public FileComponentField(final Field paField) {
		initComponents();
		//Load File Chooser in background thread
		loadFileChooser(paField);
	}

	private void loadFileChooser(final Field paField) {
		aFileChooser = new JFileChooser();
		if (paField.hasParam("JFileChooser.type")) {
			aFileChooser.setDialogType(paField.getParam("JFileChooser.type").intValue());
		}
		if (paField.hasParam("JFileChooser.fileSelectionMode")) {
			aFileChooser.setFileSelectionMode(paField.getParam("JFileChooser.fileSelectionMode").intValue());
			if (paField.getParam("JFileChooser.fileSelectionMode").intValue() == JFileChooser.DIRECTORIES_ONLY) {
				aFileChooser.setDialogTitle("Vyber zložku");
			}
			else {
				aFileChooser.setDialogTitle("Vyber súbor");
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jButton1.setText("Open");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Nájdi súbor...");
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
		if (aFileChooser != null && aFileChooser.showDialog(this, "Ok") == JFileChooser.APPROVE_OPTION) {
			aSelected = aFileChooser.getSelectedFile();
			jTextField1.setText(aSelected.getAbsolutePath());
		}
    }//GEN-LAST:event_jButton1ActionPerformed

	public File getFile() {
		return aSelected;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
