/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.uniza.fri.duracik2.gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.ExecutionException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.SwingWorker;
import sk.uniza.fri.duracik2.gui.reflection.MethodExecuteListnerer;
import sk.uniza.fri.duracik2.gui.reflection.Metoda;
import sk.uniza.fri.duracik2.gui.reflection.Reflektor;
import sk.uniza.fri.duracik2.gui.reflection.Tools;

/**
 *
 * @author Unlink
 */
public class SimpleWindow extends javax.swing.JFrame {

	private Reflektor<?> aReflektor;
	private Icon aSpinner = new javax.swing.ImageIcon(getClass().getResource("/sk/uniza/fri/duracik2/gui/ajax-loader.gif")); // NOI18N

	/**
	 * Creates new form Main
	 */
	public SimpleWindow(Reflektor<?> reflektor) {
		aReflektor = reflektor;
		initComponents();
		jComboBox1.setModel(new DefaultComboBoxModel(aReflektor.getMedoty().toArray()));
		jComboBox1.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent paE) {
				insertMethodPanel();
			}
		});
		insertMethodPanel();
		aReflektor.addExecutionListnerer(new MethodExecuteListnerer() {

			@Override
			public void methodExecuted(final String paName, final Object[] paRams, final Object paResult) {
				java.awt.EventQueue.invokeLater(new Runnable() {
					@Override
					public void run() {
						jColorTextPane1.append(Color.BLUE.darker(), paName.trim() + "\n", JColorTextPane.TYPE_UNDERLINE | JColorTextPane.TYPE_BOLD);
						if (paResult instanceof Iterable) {
							boolean head = false;
							for (Object x : (Iterable) paResult) {
								if (!head && x instanceof IGuiPrintListHead) {
									((IGuiPrintListHead) x).printListHead(jColorTextPane1);
									jColorTextPane1.append("\n");
									head = true;
								}
								vypis(x);
								jColorTextPane1.append("\n");
							}
							jColorTextPane1.append("\n");
						}
						else if (paResult instanceof Exception) {
							jColorTextPane1.append(Color.RED, "> " + Tools.getErrorMessage((Exception) paResult) + "\n\n");
						}
						else {
							vypis(paResult);
							jColorTextPane1.append("\n");
						}
					}
				});
			}
		});

		setLocationRelativeTo(null);
	}

	private void vypis(Object obj) {
		if (obj instanceof IGuiPrint) {
			((IGuiPrint) obj).print(jColorTextPane1);
		}
		else if (obj instanceof Boolean) {
			boolean val = (Boolean) obj;
			jColorTextPane1.append("> ");
			if (val) {
				jColorTextPane1.append(Color.GREEN.darker().darker(), "OK");
			}
			else {
				jColorTextPane1.append(Color.RED, "Chyba");
			}
		}
		else if (obj == null) {
			jColorTextPane1.append("> null\n");
		}
		else {
			jColorTextPane1.append("> " + obj.toString() + "\n");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jColorTextPane1 = new sk.uniza.fri.duracik2.gui.JColorTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exportný systém");

        jLabel1.setText("Metóda:");

        jScrollPane1.setViewportView(jColorTextPane1);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(jPanel1);

        jButton1.setText("Vykonaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(171, 171, 171)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
		jButton1.setIcon(aSpinner);
		jButton1.setEnabled(false);
		jLabel2.setText("");
		new SwingWorker<Long, Double>() {

			@Override
			protected Long doInBackground() throws Exception {
				long begin = System.nanoTime();
				((Metoda) jComboBox1.getSelectedItem()).submitMethod();
				return System.nanoTime() - begin;
			}

			@Override
			protected void done() {
				jButton1.setIcon(null);
				jButton1.setEnabled(true);
				try {
					jLabel2.setText(String.format("%.3f ms", get() / 1000000.0d));
				}
				catch (InterruptedException | ExecutionException ex) {
				}
			}

		}.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		jColorTextPane1.clear();
    }//GEN-LAST:event_jButton2ActionPerformed


	private void insertMethodPanel() {
		Metoda selected = (Metoda) jComboBox1.getSelectedItem();
		jPanel1.removeAll();
		jPanel1.add(selected.getInputPanel());
		jScrollPane2.validate();
		jPanel1.validate();
		jPanel1.repaint();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private sk.uniza.fri.duracik2.gui.JColorTextPane jColorTextPane1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
